### PR TITLE
Fix compling errors on various platforms/consoles

### PR DESCRIPTION
**Pull request by HoussineMehnik**
- Fixed some include paths case sensitive
- Fixed CogImguiInputHelper.h including itself
- Added missing includes
- Added missing forward declarations
- Fixed enums forward declarations
- Fixed "TCHAR_TO_ANSI" and const char* formatting issues
- Fixed "sscanf" on Linux

### CODE REVIEW

**Comment by arnaud-jamin** [comment]
Thanks a lot for this contribution!

**Comment by arnaud-jamin** [comment]
I integrated everything but the first change I commented above. (#include "CogDebugSettings.h")
Don't hesitate to tell me if this is still causing an error. 
Thanks !!!

**Comment by HoussineMehnik** [comment]
Cool!
Tested with your change and everything works fine :)

**Comment by HoussineMehnik** [comment]
I just found that I have a local modification on CogCommon.Build.cs this is why I didn't got any issue with including "CogDebugSettings.h".
"CogCommon" need to have a dependency to "CogDebug" , otherwise the build will fail on non unity builds.

**Comment by arnaud-jamin** [comment]
Could you copy paste the compiler error ?
Thanks

**Comment by HoussineMehnik** [comment]
"fatal error C1083: Cannot open include file: 'CogDebugSettings.h': No such file or directory"

But it disappeared again, I think there is something wrong with our build/validation configuration :)

**Comment by arnaud-jamin** [comment]
Do you know this error happens when compiling what file ?
It is in the sample or a modified version ?
CogDebugSettings.h should always be inside  #if ENABLE_COG

**Comment by HoussineMehnik** [comment]
Oh nvm , sorry I didn't pay attention to it, CogDebugSettings.h was outside of #if ENABLE_COG 😅

**Comment by arnaud-jamin** [comment]
Ok cool. I know it is not intuitive as cog modules don't do that. But they get stripped instead.

**Pull request merged**
